from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_OAEP
from Crypto.Util import number

data = b'This is a secret message.'
key = RSA.generate(2048)
public_key = key.public_key()
private_key = key

ciphertext = PKCS1_OAEP.new(public_key).encrypt(data)
print("Decrypted message:", PKCS1_OAEP.new(private_key).decrypt(ciphertext).decode())

p = number.getPrime(128)
g = 2
private_key = number.getRandomRange(2, p - 2)
public_key = pow(g, private_key, p)
print("Public key generated by Diffie-Hellman:", public_key)
